name: win-x86

on:
  push:
    branches: ["zig"]
  pull_request:
    branches: [ "zig" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: Build
        run: zig build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dinput8.dll
          path: zig-out/bin/dinput8.dll

